services:
  nodem:
    image: ghcr.io/minoplhy/nodem:latest
    container_name: nodem
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "34234:34234" # ECH SSH pull server port
    environment:
      - BASE_PATH=/
      - PORT=8080
      - ECH_SSH_PORT=34234
    volumes:
      - ./nodem_data:/app/data
    networks:
      - nodem_net

networks:
  nodem_net:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
        - subnet: fd00:cafe:face::/64
