package agent

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateMasterIncludesConf creates a unified ech_includes.conf referencing all active clusters.
func GenerateMasterIncludesConf(storageDir string) error {
	if err := os.MkdirAll(storageDir, 0755); err != nil {
		return fmt.Errorf("failed creating storage dir: %w", err)
	}

	entries, err := os.ReadDir(storageDir)
	if err != nil {
		return fmt.Errorf("failed reading storage dir: %w", err)
	}

	stateFile := filepath.Join(storageDir, "agent_state.json")
	localState := LoadState(stateFile)
	nameMap := make(map[int64]string)
	for _, cs := range localState.Clusters {
		if cs.ClusterID > 0 {
			nameMap[cs.ClusterID] = cs.ClusterName
		}
	}

	var sb strings.Builder
	sb.WriteString("# Automatically generated by nodem-agent - multi-cluster configuration\n")

	hasEntries := false
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		clusterDir := filepath.Join(storageDir, entry.Name())
		currPath := filepath.Join(clusterDir, "ech_current.pem")
		prevPath := filepath.Join(clusterDir, "ech_previous.pem")

		if _, err := os.Stat(currPath); err == nil {
			hasEntries = true
			clusterID, isClusterDir := ParseClusterIDFromDir(entry.Name())
			if isClusterDir {
				clusterName := nameMap[clusterID]
				if clusterName != "" {
					sb.WriteString(fmt.Sprintf("\n# Cluster ID %d (%s)\n", clusterID, clusterName))
				} else {
					sb.WriteString(fmt.Sprintf("\n# Cluster ID %d\n", clusterID))
				}
			} else {
				sb.WriteString(fmt.Sprintf("\n# Cluster: %s\n", entry.Name()))
			}
			sb.WriteString(fmt.Sprintf("ssl_ech_file \"%s\";\n", currPath))
			if _, err := os.Stat(prevPath); err == nil {
				sb.WriteString(fmt.Sprintf("ssl_ech_file \"%s\";\n", prevPath))
			}
		}
	}

	if !hasEntries {
		sb.WriteString("# No active ECH clusters currently assigned to this node.\n")
	}

	includesPath := filepath.Join(storageDir, "ech_includes.conf")
	tmpPath := includesPath + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed writing ech_includes.conf.tmp: %w", err)
	}
	return os.Rename(tmpPath, includesPath)
}
